### ISSUE TITLE
Doesn't build with rust 1.30.1

### ISSUE THREAD

**Issue by estokes** [serenity-rs/serenity#433]
Compiling serenity v0.5.10                                                   
error[E0277]: the trait bound `hyper::client::Request<hyper::net::Fresh>: multipart::client::HttpRequest` is not satisfied
    --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.5.10/src/http/raw.rs:1483:23
     |                                                                          
1483 |     let mut request = Multipart::from_request(request)?;                 
     |                       ^^^^^^^^^^^^^^^^^^^^^^^ the trait `multipart::client::HttpRequest` is not implemented for `hyper::client::Request<hyper::net::Fresh>`
     |                                                                          
     = note: required by `<multipart::client::Multipart<()>>::from_request`     
                                                                                
error[E0277]: the trait bound `hyper::client::Request<hyper::net::Fresh>: multipart::client::HttpRequest` is not satisfied
    --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/serenity-0.5.10/src/http/raw.rs:1483:23
     |                                                                          
1483 |     let mut request = Multipart::from_request(request)?;                 
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `multipart::client::HttpRequest` is not implemented for `hyper::client::Request<hyper::net::Fresh>`
                                                                                
error: aborting due to 2 previous errors                                        
                                                                                
For more information about this error, try `rustc --explain E0277`.             
error: Could not compile `serenity`.                                            

To learn more, run the command again with --verbose.

**Comment by zeyla** [comment]
Try a `cargo update` and `cargo clean` and then re-building.

**Comment by estokes** [comment]
That worked. Sorry about that.
